### ISSUE TITLE
Bitleaker bootloader is not published

### ISSUE THREAD

**Issue by jagotu** [kkamagui/bitleaker#1]
When trying to run bootstrap, it attempts this step:

`git clone https://github.com/kkamagui/bitleaker-grub.git`

However, that repository doesn't seem to be published yet. Are you planning on releasing that?

**Comment by kkamagui** [comment]
Hi @jagotu , 

thank you for the notification. I just published the repository.

If you have any problem, please let me know.

Best regards,

Seunghun

**Comment by jagotu** [comment]
Thanks.
